FROM node:17.1.0-buster-slim

# Install required tools or dependencies for mkcert
RUN apt update && \
    apt install --no-install-recommends -y libnss3-tools wget ca-certificates

# Install local certificate manager for HTTPS (mkcert)
RUN wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 && \
    mv mkcert-v1.4.3-linux-amd64 /usr/local/bin/mkcert && \
    chmod +x /usr/local/bin/mkcert

# COPY
WORKDIR /opt

COPY certificates/cert.pem .
COPY certificates/key.pem .
ENV CAROOT=/opt
RUN mkcert -install

# Install npm dependencies
RUN npm install express

ARG SERVER_LOCATION
COPY $SERVER_LOCATION/server.js .
COPY $SERVER_LOCATION/public/ public/.

ENV CERT=./cert.pem
ENV KEY=./key.pem
CMD ["node", "server.js"]
