name: tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Install pip
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends python3-pip tree
      - name: python linting
        run: |
          pip3 install flake8
          flake8 . --show-source --statistics
      - name: Install docker compose v2
        run: |
          mkdir -p $HOME/.docker/cli-plugins
          curl -L https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o $HOME/.docker/cli-plugins/docker-compose
          chmod +x $HOME/.docker/cli-plugins/docker-compose
      - name: Create TLS certificates
        run: make create-certs
      - name: Launch lab
        run: docker compose up -d
      - name: Test FLEDGE with simple auction
        run: make test-auction
